### ISSUE TITLE
Avoid triggering print page on the printer screen when a bgcode is uploaded thru the Project tab of PrusaLink

### ISSUE THREAD

**Issue by LoakAudio** [prusa3d/Prusa-Link#969]
Hi all,
New to MK3.5 and PrusaLink, I've found an annoying behavior : I use to slice files on a laptop and upload them to the printer via the "Project tab" of PrusaLink.
Sometimes I need to change a parameter into a sliced file already uploaded but, if the file has been the first uploaded, the "Print page" has been triggered on the printer with this file and it can't be deleted.
Keeping this behavior via the "Dashboard Tab" can be a good thing but could you change this when it's done via the "Projects Tab" ? allowing the user to play freely with the already uploaded files.

Thanks

**Comment by 3d-gussner** [comment]
The PrusaLink on MINI, MK3.5, MK3.9, MK4 and XL is running on the main controller board.
Please close this issue here, which is only for the MK2.5/S and MK3/S/+ and SBC like a RPi.
Check in the [Prusa-Buddy-Firmware repository](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues) if that is already requested or reopen it there.
